name: Build pkgdown Site

on:
  push:
    branches:
      - main
      - master

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install pkgdown and dependencies
        run: Rscript -e 'install.packages("pkgdown"); remotes::install_deps(dependencies = TRUE)'
      - name: Build Site
        run: Rscript -e 'pkgdown::build_site()'
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
